FROM amazon/aws-lambda-python:3.13-x86_64

ARG DUCKDB_VERSION=1.3.2

# Install dependencies
RUN dnf update -y && dnf install -y zip 

# Get DuckDB Python package and package it for Lambda Layer
RUN mkdir -p /tmp/duckdb-${DUCKDB_VERSION} && \
    cd /tmp/duckdb-${DUCKDB_VERSION} && \
    pip install duckdb==${DUCKDB_VERSION} --no-cache-dir -t . && \
    mkdir -p /tmp/python && \
    cp -r ./* /tmp/python/ && \
    cd /tmp && \
    zip -r duckdb-${DUCKDB_VERSION}.zip python

