name: Test workflow
on:
  workflow_dispatch:
  push:
    branches:
      - ft/auto-readme

jobs:
  step1:
    name: Step 1
    runs-on: ubuntu-latest
    outputs:
      layer-version: ${{ steps.publish.outputs.layer-version }}
    strategy:
      matrix:
        architecture: [x86_64, arm64]

    steps:
      - name: Test Publish
        id: publish
        run: |
          # Set output for layer version
          echo "layer-version=1" >> $GITHUB_OUTPUT

  step2:
    name: Step 2
    needs: step1
    runs-on: ubuntu-latest
    steps:
      - name: Use Layer Versions
        run: |
          echo "Layer Version: ${{ needs.step1.outputs.layer-version }}"
